### ISSUE TITLE
OSGeo4W-NG Missing Shortcuts

### ISSUE THREAD

**Issue by Saijin-Naib** [jef-n/OSGeo4W#1]
OSGeo4W-NG does not seem to generate the "QGIS3" shortcut as well as the QGIS 3.x.x with GRASS 7.8.x shortcut like the older OSGeo4W installers would.

![image](https://user-images.githubusercontent.com/19295950/109994265-27106500-7cdb-11eb-81f2-fe53805771af.png)

![image](https://user-images.githubusercontent.com/19295950/109994191-0f38e100-7cdb-11eb-9cab-4729a4124cbb.png)

**Comment by jef-n** [comment]
Because the main link now includes GRASS if available.
